import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { ArticleService } from '../../shared/services/articles.service';
import { ArticleModel } from '../../interfaces/article-model';
import { UserService } from '../../shared/services/user.service';

@Component({
  selector: 'app-add-article',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './add-article.component.html',
  styleUrl: './add-article.component.css'
})
export class AddArticleComponent implements OnInit {
  articleForm!: FormGroup;
  blogId!: string;
  currentUserId: string | null = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private fb: FormBuilder,
    private articleService: ArticleService,
    private userService: UserService
  ) {}

  ngOnInit(): void {
    this.blogId = this.route.snapshot.paramMap.get('blogId')!;
    this.initializeForm();
    this.setCurrentUser();
  }

  async setCurrentUser(): Promise<void> {
    const user = await this.userService.getCurrentUser();
    this.currentUserId = user?.id || null;
  }

  initializeForm(): void {
    this.articleForm = this.fb.group({
      title: [''],
      content: ['']
    });
  }

  async saveArticle(): Promise<void> {
    if (this.currentUserId) {
      const formValues = this.articleForm.value;
      const newArticle: ArticleModel = {
        id: '', // Will be generated by the backend
        authorId: this.currentUserId,
        blogId: this.blogId,
        title: formValues.title,
        content: formValues.content,
        created: new Date(), // Current timestamp or as per backend requirement
        updated: new Date(), // Current timestamp or as per backend requirement
      };
      await this.articleService.addArticle(newArticle);
      this.router.navigate([`/blogs/${this.blogId}/articles`]);
    } else {
      alert('Unable to determine the current user.');
    }
  }

  cancel(): void {
    this.router.navigate([`/blogs/${this.blogId}/articles`]);
  }
}
